num1=float(input("Enter 1 number:"))
num2=float(input("Enter 2 number:"))
num3=float(input("Enter 3 number:"))
num4=float(input("Enter 4 number:"))
num5=float(input("Enter 5 number:"))
print("average of five number:",(num1+num2+num3+num4+num5)/5)
